INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:10:50] "GET / HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:26:24] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:26:52] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:26:57] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:27:11] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:27:17] "[33mGET /index HTTP/1.1[0m" 404 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:27:29] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:34:33] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 11:34:44] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:43:28] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:43:35] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:43:52] "[33mGET /static/news/index.html HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:46:36] "[33mGET /static/news/index.html HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:46:39] "[33mGET /static/news/index.html HTTP/1.1[0m" 404 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:46:48] "[33mGET /static/news/index.html HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:47:12] "[33mGET /android/static/news/index.html HTTP/1.1[0m" 404 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:49:21] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:06] "[33mGET /android/static/news/html/index.html HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:10] "GET /static/news/html/index.html HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:28] "GET /static/news/html/other.html HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:28] "GET /static/news/css/reset.css HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/css/jquery.pagination.css HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/js/jquery-1.12.4.min.js HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/css/main.css HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/js/jquery.pagination.min.js HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/js/other.js HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/images/logo.png HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/images/person01.png HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/images/user_pic.png HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/images/focus_icons.png HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/images/pic_code.png HTTP/1.1" 200 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 15:50:29] "GET /static/news/images/clock.png HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 16:15:13] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 16:15:17] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 16:19:01] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 16:19:10] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225  * Restarting with stat
WARNING _internal.py:225  * Debugger is active!
INFO _internal.py:225  * Debugger PIN: 729-749-637
INFO _internal.py:225 127.0.0.1 - - [24/Jun/2021 17:18:36] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:225 127.0.0.1 - - [25/Jun/2021 14:49:23] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 127.0.0.1 - - [25/Jun/2021 14:49:43] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 14:54:37] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 14:54:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 14:54:45] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 14:55:03] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 14:55:05] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 14:55:11] "GET /index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:03:12] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:03:17] "[33mGET /index HTTP/1.1[0m" 404 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:03:29] "GET /passport/index HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:04:09] "[33mGET /sn/index HTTP/1.1[0m" 404 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:04:12] "[33mGET /sn/index HTTP/1.1[0m" 404 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:05:23] "GET /sn/index HTTP/1.1" 200 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:08:22] "[33mGET /sn/add HTTP/1.1[0m" 404 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:08:46] "GET /sn/add HTTP/1.1" 200 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:08:49] "GET /sn/add HTTP/1.1" 200 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:08:57] "GET /sn/delete HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:44:39] "[33mGET / HTTP/1.1[0m" 404 -
ERROR app.py:1891 Exception on /sn/add [GET]
Traceback (most recent call last):
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\huang\Desktop\py_control\android\admin\sn\views.py", line 17, in sn_add
    md = hashlib.md5('salt')  # bytes
TypeError: Unicode-objects must be encoded before hashing
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:44:49] "[35m[1mGET /sn/add HTTP/1.1[0m" 500 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /sn/add [GET]
Traceback (most recent call last):
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\huang\Desktop\py_control\android\admin\sn\views.py", line 17, in sn_add
    md = hashlib.md5(bytes('salt'))  # bytes
TypeError: string argument without an encoding
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:45:23] "[35m[1mGET /sn/add HTTP/1.1[0m" 500 -
ERROR app.py:1891 Exception on /sn/add [GET]
Traceback (most recent call last):
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\huang\.virtualenvs\py_control\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\huang\Desktop\py_control\android\admin\sn\views.py", line 17, in sn_add
    md = hashlib.md5(bytes('salt'))  # bytes
TypeError: string argument without an encoding
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:45:25] "[35m[1mGET /sn/add HTTP/1.1[0m" 500 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:46:37] "GET /sn/add HTTP/1.1" 200 -
INFO _internal.py:225 192.168.147.1 - - [25/Jun/2021 15:46:50] "GET /sn/add HTTP/1.1" 200 -
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
INFO _internal.py:225  * Running on http://192.168.147.1:5001/ (Press CTRL+C to quit)
